<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Test_aTMfbjo5UN_1_2</name>
   <tag></tag>
   <elementGuidId>01f43bf2-4c85-4ec8-a4da-ec0fcfe7241d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_content']/div[3]/div/div/div[2]/div/table/tbody/tr/td[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.a2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/Mediabox-independence/Base/ExecAction?action=AfficheFichesProjet&amp;IDSession=MBI!REL_SEPHORA!1J0OL55F5AVCV0EBXI69OO46VYEW3FYATMAIX704&amp;num=POCEQI684K&amp;id_project=MI001040' and (text() = 'Test_aTMfbjo5UN' or . = 'Test_aTMfbjo5UN')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Mediabox-independence/Base/ExecAction?action=AfficheFichesProjet&amp;IDSession=MBI!REL_SEPHORA!1J0OL55F5AVCV0EBXI69OO46VYEW3FYATMAIX704&amp;num=POCEQI684K&amp;id_project=MI001040</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test_aTMfbjo5UN</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_content&quot;)/div[@class=&quot;d-flex flex-column-fluid&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;card card-custom bg-grey&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;table-content&quot;]/table[1]/tbody[1]/tr[@class=&quot;datatable-row&quot;]/td[3]/a[@class=&quot;a2&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content']/div[3]/div/div/div[2]/div/table/tbody/tr/td[3]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Test_aTMfbjo5UN')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project name'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test_7Wi3rWQZs7'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test_aTMfbjo5UN']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Mediabox-independence/Base/ExecAction?action=AfficheFichesProjet&amp;IDSession=MBI!REL_SEPHORA!1J0OL55F5AVCV0EBXI69OO46VYEW3FYATMAIX704&amp;num=POCEQI684K&amp;id_project=MI001040')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
   </webElementXpaths>
</WebElementEntity>
