#Author: your.email@your.domain.com
#Keywords Summary :
#Feature: List of scenarios.
#Scenario: Business rule through list of steps with arguments.
#Given: Some precondition step
#When: Some key actions
#Then: To observe outcomes or validation
#And,But: To enumerate more Given,When,Then steps
#Scenario Outline: List of steps for data-driven as an Examples and <placeholder>
#Examples: Container for s table
#Background: List of steps run before each of the scenarios
#""" (Doc Strings)
#| (Data Tables)
#@ (Tags/Labels):To group Scenarios
#<> (placeholder)
#""
## (Comments)
#Sample Feature Definition Template



@Starpack_Usermanagement
Feature: Creation of User - Cancel
  I wan to verify that user is not created if I click on the cancel button
  
 
  @Before_Test
  Scenario Outline: User can see user management on the LHS menu
    Given I am on Mediabox Starpack
    When I login as suser
    And I see the settings in the menu
    And I click on the menu > Settings
    Then I see the user management in the menu
    
      
     @Test
  Scenario Outline: User can get access to creation user page
    Given I see the usermanagement in the menu  
    When I click on usermanagement button
    And I click on Create user button
    Then I see the user creation page
        
    @Test
  Scenario Outline: User can see login is autogenerated
    Given I am on the user creation page
    When I enter text in First name field 
    And I enter text in Email field
    And I select diadeis from company list field
    And I select Commercial Support from user role list field
    And I scroll down
    And I select Dia from Brand multiplelist field
    Then I see the login is generated
    
        @Test
  Scenario Outline: User can see login is autogenerated
    Given I am on the user creation page
    When I click on cancel button
   	And I search for email cancel@testautodiadeis.com on the usermanagement page
    Then I see the message 'No matching records'
    
 @After_Test
  Scenario Outline: User Logout
    Given I am on the usermanagement page
    Then I logout as suser
   